##print("동해물과 백두산이\n마르고 닳도록\n\t하느님이\"bow\"하사 우리나라 만세")
##print("\"\'습관\'보다\n\t강한 것은 없다.\"")
##import turtle
##turtle.shape("turtle")
##turtle.write("welcome to the python world",True, font=("arial", 20, "bold"))
##turtle.circle(20,150)
##print("apple")
##print("juice")
##print("apple""juice")
##print("apple","juice")
##print("apple","juice",sep='~')
##print("apple","juice",end=' is ')
##print("tasty")
##input("what is your favorite juice? ")
##print(input("what is your favorite juice? "))
##print(input(" 이름 : "))
##print(input(" 학년 : "))
##print(input(" 반 : "))
##print("A","B","C","D",sep='\n')
##import turtle
##turtle.shape("turtle")
##turtle.circle(100)
##turtle.circle(150)
##turtle.circle(200)

